- hosts: laptop-thinkpad-p14s-gen3-1
  tasks:
    - name: Install system specific packages
      shell: |
        arch-chroot /mnt pacman -Sy --noconfirm bluez \
                                                bluez-utils \
                                                fprintd \
                                                intel-compute-runtime \
                                                intel-gpu-tools \
                                                intel-media-driver \
                                                iwd \
                                                lib32-libvdpau \
                                                lib32-vulkan-intel \
                                                libvdpau \
                                                libvdpau-va-gl \
                                                vulkan-intel \
                                                wireless-regdb

    - name: Configure GPU
      copy:
        src: etc/modprobe.d/i915.conf
        dest: /mnt/etc/modprobe.d/i915.conf

    - name: Configure bluetooth
      block:
        - shell: arch-chroot /mnt systemctl enable bluetooth

    - name: Configure wireless-regdb
      block:
        - copy:
            content: |
              WIRELESS_REGDOM="DE"
            dest: /mnt/etc/conf.d/wireless-regdom
