- hosts: pc-amd-ryzen-amd-radeon-1
  tasks:
    - name: Install system specific packages
      shell: |
        arch-chroot /mnt pacman -Sy --noconfirm amdgpu_top \
                                                amd-ucode \
                                                bluez \
                                                bluez-utils \
                                                lib32-mesa \
                                                lib32-vulkan-radeon \
                                                libva-mesa-driver \
                                                libva-utils \
                                                mesa \
                                                rocm-hip-sdk \
                                                rocm-opencl-sdk \
                                                vulkan-icd-loader \
                                                vulkan-radeon

    - name: Configure bluetooth
      block:
        - shell: arch-chroot /mnt systemctl enable bluetooth
