# The USB/IP attach socket (usbip-knx-license-stick.service) has SO_KEEPALIVE
# set by `usbip attach`, with the kernel's global timing: Arch already shortens
# the idle time to 120 s (/usr/lib/sysctl.d/10-arch.conf), but the stock 9
# probes every 75 s mean a dead peer is noticed only after ~13 min. If the
# USB/IP server vanishes or this laptop's address changes while the stick is
# attached, vhci-hcd keeps a dead attach that long and the timer sees nothing
# to fix. 3 probes every 10 s drop a dead peer ~150 s after the last traffic.
# Applies to every keepalive-enabled socket on this host; they only notice dead
# peers sooner.
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 3
